routes/web.php
<?php

use VCN\Helpers\ExternalApiHelper;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
|
*/

Route::group(['prefix' => 'auth'], function(){
    Auth::routes();
    //Auth::routes(['verify' => true]);
});

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->middleware('auth');
//Resources?

//Area : archivos
Route::get('/files/viajeros/{viajero_id}/{file?}', 'Manage\ManageController@serveFileViajeros')->middleware('auth.area');
Route::get('/files/bookings/{viajero_id}/{file?}',  ['as' =>'file.booking', 'uses' => 'Manage\ManageController@serveFileBookings'] )->middleware('auth.area');
Route::get('/files/viajeros/{viajero_id}/{booking_id}/{file?}', 'Manage\ManageController@serveFileViajerosBooking')->middleware('auth.area');
Route::get('/files/convocatorias/facturas/{file?}', 'Manage\ManageController@serveFileFacturas')->middleware('auth.area');
Route::get('/manage/cursos/pocket-guide-pdf/{id}/{lang}', ['as' =>'manage.cursos.pocket-guide', 'uses' => 'Manage\Cursos\CursosController@getPocketGuidePdf'])->middleware('auth.area');

Route::get('/files/firmar/{viajero_id}/{file?}',  ['as' =>'file.firma', 'uses' => 'Manage\ManageController@serveFileFirma'] )->middleware('auth.area');

//chat
// Route::get('/chat/test/{chatId?}', 'Web\ChatController@test')->name('web.chat.test');
// Route::post('/chat/create', 'Web\ChatController@create')->name('web.chat.create');
// Route::post('/chat/status', 'Web\ChatController@checkStatus')->name('web.chat.status');
// Route::post('/chat/mensaje', 'Web\ChatController@postMensaje')->name('web.chat.mensaje');
// Route::post('/chat/formulario', 'Web\ChatController@postFormulario')->name('web.chat.formulario');

Route::get('/ac/tests', function(){
    return ExternalApiHelper::AC_contactsAdd();
});

/*
|--------------------------------------------------------------------------
| Ejemplo Routes Translate
|--------------------------------------------------------------------------
 */


// Route::get('/lang/{lang?}', ['as' => 'cambio.idioma', 'uses' => 'Web\WebController@cambioIdioma']);

Route::get('/iccic/cataleg.html', function(){
    return Redirect::to('cataleg.html');
});
// Route::get('{slug?}.php', ['as' =>'web.oldweb', 'uses' => 'Web\WebController@oldWeb']);
// Route::get('/translations', '\Barryvdh\TranslationManager\Controller@getIndex');
// Route::get('/translations/view/{group?}', '\Barryvdh\TranslationManager\Controller@getView');

Route::get('/ajax/{curso_id}', ['as' =>'ajax.info', 'uses' => 'Web\WebController@ajaxInfo']);

Route::post('/register', ['as' =>'web.register', 'uses' => 'Web\WebController@postRegister']);

Route::get('/info/{curso_id}', ['as' =>'web.proveedor', 'uses' => 'Web\WebController@getProveedor']);

Route::localizedGroup(function () {

    Route::get('/test-vue', ['as' =>'web.buscar.vue', 'uses' => 'Web\WebController@buscarByPaisVue']);
    Route::get('/test-vue-api', ['as' =>'web.buscar.vue.api', 'uses' => 'Web\WebController@buscarByPaisVueApi']);

    Route::transGet('web.catalogo-slug', ['as' =>'web.catalogo', 'uses' => 'Web\WebController@getCatalogo']);
    Route::transGet('web.contacto-slug', ['as' =>'web.contacto', 'uses' => 'Web\WebController@getContacto']);
    Route::transGet('web.inscripcion-slug', ['as' =>'web.inscripcion', 'uses' => 'Web\WebController@getInscripcion']);

    Route::post('web.catalogo-info', ['as' =>'web.catalogo-info', 'uses' => 'Web\WebController@postCatalogoInfo']);
    Route::post('web.curso-info', ['as' =>'web.curso-info', 'uses' => 'Web\WebController@postCursoInfo']);
    Route::post('web.contacto', ['as' =>'web.contacto', 'uses' => 'Web\WebController@postContacto']);
    Route::post('web.informacion', ['as' =>'web.informacion', 'uses' => 'Web\WebController@postInformacion']);

    Route::get('/landing/{slug}', ['as' =>'web.landing', 'uses'=> 'Web\WebController@getLanding']);
    Route::get('/landing/{slug}/catalogo', ['as' =>'web.landing.catalogo', 'uses'=> 'Web\WebController@getLandingCatalogo']);
    Route::post('/landing/{landing}', ['as' =>'web.landing.post', 'uses'=> 'Web\WebController@postLanding']);

    Route::get('/catalogos/{pdf?}', ['as' =>'web.pdf', 'uses' => 'Web\WebController@pdf']);
    Route::get('/translations', '\Barryvdh\TranslationManager\Controller@getIndex');
    Route::get('/translations/view/{group?}', '\Barryvdh\TranslationManager\Controller@getView');
    Route::get('/', ['as' =>'web.index', 'uses'=> 'Web\WebController@index']);

    Route::transPost('routes.buscar', ['as' =>'web.buscar.pais', 'uses' => 'Web\WebController@buscarByPais']);

    Route::transPost('web.buscar-slug', ['as' =>'web.buscar', 'uses' => 'Web\WebController@buscar']);
    Route::transGet('web.buscar-slug', ['as' =>'web.buscar', 'uses' => 'Web\WebController@buscar']);
    Route::transGet('web.cursos-en-promocion', ['as' =>'web.promoscursos', 'uses' => 'Web\WebController@promoscursos']);
    Route::get('{page?}.html', ['as' =>'web.pagina', 'uses' => 'Web\WebController@pagina']);

    // /pais/{pais?}
    // Route::get('/pais/{pais?}', ['as' =>'web.pais', 'uses' => 'Web\WebController@getPais']);
    // /pais/{pais?}/{course_slug?}.html
    // Route::transGet('routes.pais_curso', ['as' =>'web.pais-curso', 'uses' => 'Web\WebController@getPaisCurso']);

    //Estas rutas son configurables por plataforma: para categorias, especialidades y pais:
    // Route::get('/{cat?}/{course_slug?}.html', ['as' =>'web.curso', 'uses' => 'Web\WebController@curso']);
    // Route::get('/{cat?}/getpdf/{id?}', ['as' =>'web.getPdfcurso', 'uses' => 'Web\WebController@getPdfcurso']);
    // Route::get('/{cat?}', ['as' =>'web.categoria', 'uses' => 'Web\WebController@categoria']);
    // Route::get('/{cat?}/{subcat?}', ['as' =>'web.subcategoria', 'uses' => 'Web\WebController@subcategoria']);
    // Route::get('/{cat?}/{subcat?}/{subcatdet?}', ['as' =>'web.subcategoria', 'uses' => 'Web\WebController@subcategoriadetalle']);

    //Estructura nueva (e2): ejemplo: http://viajaconnosotros.dev/nueva/aprender-ingles-en-el-extranjero/jovenes/grupos-con-monitor/carlingford-camp.html
    Route::get('/wn/{query?}', ['as' =>'web.wn', 'uses' => 'Web\WebController@getCategoriaWeb'])->where('query','.+');

    $v = ConfigHelper::config('web_estructura');
    if( $v == 2)
    {
        
    }
    elseif( $v == 1)
    {

    }

    //e2: Todas estas desaparacen:
    Route::get('/{param1?}/{slug?}.html', ['as' =>'web.curso', 'uses' => 'Web\WebController@raizCurso', 'middleware'  => [ 'web','visitas' ] ]);
    Route::get('/{param1?}', ['as' =>'web.raiz', 'uses' => 'Web\WebController@raiz']);
    Route::get('/{param1?}/{param2?}', ['as' =>'web.raiz.sub', 'uses' => 'Web\WebController@raizSub']);

    Route::get('/{param1?}/getpdf/{id?}', ['as' =>'web.getPdfcurso', 'uses' => 'Web\WebController@raizPdfcurso']);
    Route::get('/{param1?}/{param2?}/{param3?}', ['as' =>'web.raiz.det', 'uses' => 'Web\WebController@raizSubDet']);


    Route::transGet('routes.view', [
        'as' => 'web.view',
        'uses' => 'Web\WebController@view',
    ]);




    // Route::transGet('routes.about', function () {
    //     // return view('about');
    //     return trans('messages.about');
    // });
    // Route::transGet('routes.view', function ($id) {
    //     dd($id);
    //     return view('page', compact('id'));
    // });



});

// Route::get('/v/{id?}', ['as' =>'web.view', 'uses' => 'Web\WebController@view']);

app/Models/User.php
<?php

namespace VCN\Models;

// use Illuminate\Auth\Authenticatable;
// use Illuminate\Database\Eloquent\Model;
// use Illuminate\Auth\Passwords\CanResetPassword;
// use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
// use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

// use VCN\Models\Informes\Presupuesto;

// use VCN\Helpers\ConfigHelper;
// use Carbon;

// class User extends Model implements AuthenticatableContract, CanResetPasswordContract
// {
//     use Authenticatable, CanResetPassword;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use NotificationChannels\WebPush\HasPushSubscriptions;

use VCN\Models\Informes\Presupuesto;

use VCN\Helpers\ConfigHelper;
use Carbon;
// use Activity;

class User extends Authenticatable
{
    use Notifiable;
    use HasPushSubscriptions;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'email', 'password', 'fname', 'lname', 'roleid', 'status', 
        'config', 'plataforma', 'oficina_id',
        'es_guest','last_activity'
    ];
    // protected $guarded = ['_token'];

    protected $dates = ['login_last'];

    protected $casts = [
        'compra' => 'json',
        'registro' => 'json',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    public function scopePlataforma($query)
    {
        $filtro = ConfigHelper::config('propietario');
        if($filtro)
        {
            return $query->where('plataforma',$filtro);//->orWhere('plataforma',0);
        }

        return $query;
    }

    public function scopeCrm($query)
    {
        return $query->where('status','>',0)->where('roleid','<>',11)->where('roleid','<>',12)->where('roleid','<>',13);
    }

    public function scopeActivos($query)
    {
        return $query->where('status','>',0);
    }

    public function viajeros()
    {
        return $this->hasMany('\VCN\Models\Leads\Viajero', 'asign_to');
    }

    public function viajero()
    {
        return $this->hasOne('\VCN\Models\Leads\Viajero', 'user_id');
    }

    public function tutor()
    {
        return $this->hasOne('\VCN\Models\Leads\Tutor', 'user_id');
    }

    public function monitor()
    {
        return $this->hasOne('\VCN\Models\Monitores\Monitor', 'user_id');
    }

    public function getUserTutorViajeroAttribute()
    {
        if($this->viajero)
        {
            $u = User::where('username',$this->username)->where('plataforma',$this->plataforma)->where('roleid',12)->first();

            return $u ?: null;
        }

        if($this->tutor)
        {
            $u = User::where('username',$this->username)->where('plataforma',$this->plataforma)->where('roleid',11)->first();

            return $u ?: null;
        }

        return null;
    }

    public function chats()
    {
        return $this->belongsToMany("\VCN\Models\Chat\ChatSoporte", 'mc_conversation_user', 'user_id', 'conversation_id');//->withTimestamps();
    }

    public function getChatAttribute()
    {
        $ret = $this->chat_id ? \VCN\Models\Chat\ChatSoporte::find($this->chat_id) : null;
        if(!$ret)
        {
            $this->chat_id = null;
            $this->save();
        }

        return $ret;
    }

    public function getChatClienteAttribute()
    {
        $chat = $this->chat;
    }

    public function getChatAgenteAttribute()
    {
        $chat = $this->chat;
    }

    public static function getFreeForChat()
    {
        $m = 60;
        $t = Carbon::now()->subMinutes($m)->getTimestamp();

        $free =  User::where('es_guest',1)->where(function($q) {
            $q->where('chat_id', null)->orWhere('chat_id',0);
        })->first();

        if(!$free)
        {
            $free =  User::where('es_guest',1)->where(function($q) use ($t) {
                $q->where('chat_last_activity',0)->orWhere('chat_last_activity', '<', $t);
            })->orderby('chat_last_activity')->first();
        }

        $free->chat_id = null;
        $free->chat_last_activity = null;

        $free->last_activity = Carbon::now()->getTimestamp();
        $free->save();

        return $free;
    }

    public static function getChatCrmDisponibles()
    {
        // self::onlineUsers();

        $m = 10;
        $t = Carbon::now()->subMinutes($m)->getTimestamp();

        $users =  User::where('chat_admin',1)->where('last_activity','>',0)->where('last_activity', '>=', $t)->get();
        
        return $users;
    }

    public function getChatSesionCaducadaAttribute()
    {
        $m = 10;
        $t = Carbon::now()->subMinutes($m)->getTimestamp();

        return $this->chat_last_activity < $t;
    }

    public function getSesionCaducadaAttribute()
    {
        $m = 10;
        $t = Carbon::now()->subMinutes($m)->getTimestamp();

        return $this->last_activity < $t;
    }

    public function actividad()
    {
        return $this->hasMany('\VCN\Models\System\UserActividad', 'user_id');
    }

    public static function online()
    {
        $activities = Activity::users()->get();

        return $activities;
    }

    public static function onlineUsers()
    {
        $roles = User::whereNotIn('roleid',[11,12,13])->pluck('id')->toArray();
        $activities = Activity::users()->whereIn('sessions.user_id', $roles)->get();
        
        return $activities;
    }

    public static function onlineGuests()
    {
        $guests = Activity::guests(5); //5 minutos

        return $guests;
    }

    public static function onlineViajeros()
    {
        $roles = User::where('roleid',11)->pluck('id')->toArray();
        $activities = Activity::users()->whereIn('sessions.user_id', $roles)->get();

        return $activities;
    }

    public static function onlineTutores()
    {
        $roles = User::where('roleid',12)->pluck('id')->toArray();
        $activities = Activity::users()->whereIn('sessions.user_id', $roles)->get();

        return $activities;
    }

    public static function onlineMonitores()
    {
        $roles = User::where('roleid',13)->pluck('id')->toArray();
        $activities = Activity::users()->whereIn('sessions.user_id', $roles)->get();

        return $activities;
    }

    public function getFichaAttribute()
    {
        if($this->es_viajero)
            return $this->viajero;

        if($this->es_tutor)
            return $this->tutor;

        if($this->es_monitor)
            return $this->monitor;

        return null;
    }

    public function getEsAvisoFotoAttribute()
    {
        if($this->es_viajero)
        {
            if($this->ficha->booking)
            {
                return $this->ficha->booking->es_aviso_foto;
            }
        }

        if($this->es_tutor)
        {
            foreach($this->ficha->viajeros as $viajero)
            {
                if(!$viajero->booking)
                {
                    continue;
                }
                
                if($viajero->booking->es_aviso_foto)
                {
                    return true;
                }
            }
        }

        return false;
    }

    public function getIdiomaContactoAttribute()
    {
        return $this->ficha ? $this->ficha->idioma_contacto : "es";
    }

    public function getDatosCampamentoPendienteAttribute()
    {
        $ret = "<span class='badge badge-warning'><i class='fa fa-exclamation-triangle'></i></span>";

        if($this->es_viajero && $this->viajero->booking)
        {
            if($this->viajero->booking->datos_campamento_pendiente)
            {
                return $ret;
            }
        }

        if($this->es_tutor)
        {
            foreach($this->ficha->viajeros as $viajero)
            {
                if(!$viajero->booking)
                {
                    continue;
                }
                
                if($viajero->booking->datos_campamento_pendiente)
                {
                    return $ret;
                }
            }
        }

        return null;
    }

    public function getFotoDirAttribute()
    {
        if($this->es_viajero)
        {
            return "assets/uploads/monitor/";
        } 
        elseif($this->es_tutor)
        {
            return "assets/uploads/tutores/";
        }
        elseif($this->es_monitor)
        {
            return "assets/uploads/viajeros/";
        }

        return "assets/uploads/users/";
    }


    public function solicitudes()
    {
        return $this->hasMany('\VCN\Models\Solicitudes\Solicitud', 'user_id');
    }

    public function solicitudes_betweenFechas( $desde, $hasta)
    {
        $desde = Carbon::createFromFormat('!d/m/Y',$desde);
        $hasta = Carbon::createFromFormat('!d/m/Y',$hasta);
        return $this->hasMany('\VCN\Models\Solicitudes\Solicitud', 'user_id')->where('fecha','>=',$desde)->where('fecha','<=',$hasta)->get();
    }

    public function solicitudes_activas()
    {
        $status = [];
        $status[] = ConfigHelper::config('solicitud_status_futuro');
        $status[] = ConfigHelper::config('solicitud_status_archivado');

        return $this->hasMany('\VCN\Models\Solicitudes\Solicitud', 'user_id')->whereNotIn('status_id',$status);
    }

    public function solicitudes_activas_betweenFechas( $desde, $hasta)
    {
        $status = [];
        $status[] = ConfigHelper::config('solicitud_status_futuro');
        $status[] = ConfigHelper::config('solicitud_status_archivado');

        $desde = Carbon::createFromFormat('!d/m/Y',$desde);
        $hasta = Carbon::createFromFormat('!d/m/Y',$hasta);

resources/views/area/booking-schools.blade.php
<div class="row">
    <div class="col-md-12">
        
        @if( $booking->schools_area->count()>0 )
        <h4 class="text-warning">{!! trans('area.escuelas') !!}:</h4>

        <table class="table">
            <thead>
                <tr class="thead">
                    <td>{!! trans('area.escuela') !!}</td>
                    <td>{!! trans('area.fechas') !!}</td>
                    <td width="20%"></td>
                    <td width="20%"></td>
                </tr>
            </thead>
            <tbody>
            @foreach($booking->schools_area as $bfam)
                <tr>
                    <td><a data-label="{!! trans('area.verdetalles') !!}" href="{{route('area.booking.school',$bfam->id)}}">{{$bfam->school->name}}</a></td>
                    <td>
                        {!! trans('area.del') !!} {{$bfam->desde?$bfam->desde->format('d/m/Y'):"-"}}
                        {!! trans('area.al') !!} {{$bfam->hasta?$bfam->hasta->format('d/m/Y'):"-"}}
                    </td>
                    <td><a class="btn btn-block btn-primary" href="{{route('area.booking.school',$bfam->id)}}"><i class="fa fa-eye"></i> {!! trans('area.verdetalles') !!}</a></td>
                    <td><a class="btn btn-block btn-success" href="{{route('area.booking.school-pdf',$bfam->id)}}"><i class="fa fa-download"></i> {!! trans('area.descargar') !!}</a></td>
                </tr>
            @endforeach
            </tbody>
        </table>
        @endif

    </div>
</div>

resources/views/area/index.blade.php
@extends('layouts.area')


@section('content')
  
    <h2 class="text-capitalize text-success">Hola {{mb_strtolower($usuario->ficha->name)}}</h2>
    
    @if($usuario->user_tutor_viajero)
      @if($usuario->tutor)
        [@lang('area.tutor')] <a href="{{route('area.login.swap')}}">@lang('area.login_viajero')</a>
      @elseif($usuario->viajero)
        [@lang('area.viajero')] <a href="{{route('area.login.swap')}}">@lang('area.login_tutor')</a>
      @endif
    @endif



    @if( $usuario->es_tutor && !is_null($usuario->datos_campamento_pendiente) )

      <div class="alert alert-warning" role="alert">
        <a href="{{ route('area.datos.hijos') }}">
          <strong><span class='badge badge-warning'><i class='fa fa-exclamation-triangle'></i></span> @lang('area.datos_campamento_pendiente')</strong>  
        </a>
      </div>
      
    @endif
    
    <hr>

    @if($usuario->es_aviso_foto)
        <div class="row">
            <div class="col-md-10">
                <a href="{{ $usuario->es_viajero ? route('area.datos.index') : route('area.datos.hijos') }}">
                <div class="note note-warning">
                    <h4 class="block">@lang('area.booking.atencion')</h4>
                    <p>{!! trans('area.datosfoto_aviso') !!}</p>
                </div>
                </a>
            </div>
            <div class="col-md-2">

            </div>
        </div>
        <hr>
    @endif

    @if($usuario->es_monitor)
        @include('area.monitores.index', ['monitor'=> $usuario->ficha])
    @endif

    @if($usuario->es_viajero)
        @if($usuario->viajero->oficina)
        <div class="portlet light bordered">
            <div class="portlet-title tabbable-line">
                <div class="caption font-green-sharp">
                    <i class="fa fa-building fa-2x"></i>
                    <span class="caption-subject bold uppercase">{!! trans('area.mioficina') !!}: {{$usuario->viajero->oficina->name}}</span>
                </div>
                <div class="tools">
                    <a href="" class="expand btn btn-circle btn-default btn-text" data-original-title="" title=""> {!! trans('area.verdatos') !!}</a>
                </div>
            </div>
            <div class="portlet-body flip-scroll" style="display: none;">
                <div class="row">
                    <div class="col-sm-9">
                        <p>
                            <strong>{!! trans('area.tlf') !!}:</strong> {{$usuario->viajero->oficina->telefono}}
                            <br /><strong>{!! trans('area.email') !!}:</strong> <span class="text-lowercase">{{$usuario->viajero->oficina->email}}</span>
                        </p>
                        <p>
                            <strong>{!! trans('area.direccion') !!}:</strong> {{$usuario->viajero->oficina->direccion}}. {{$usuario->viajero->oficina->poblacion}}
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        @endif
    @endif

    {{-- LOPD_CHECKS 2018 --}}
    <?php
      $bArea = false;
      $u = auth()->user();
      if($u->es_viajero || $u->es_tutor || $u->es_monitor)
      {
        $bArea = true;
      }

      if(ConfigHelper::config('es_rgpd'))
      {
        $bArea = false; 
      }
    
    ?>
    @if(is_null($usuario->ficha->lopd_check1) && $bArea)

        <?php
            $bModal = false;
            if($usuario->ficha->lopd_booking_any == 2018)
            {
                $bModal = true;
            }
        ?>

        @if($bModal)
        <div class="modal fade" tabindex="-1" role="dialog" id="lopd">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">LOPD</h4>
                    </div>

                    {!! Form::open(array('id'=> 'frmLOPD', 'method'=> 'post', 'url' => route('area.datos.post'))) !!}
                    <div class="modal-body">

                        {!! Form::hidden('submit_lopd', 1) !!}

                        <div class="form-group">
                            @include('includes.form_checkbox', [ 'campo'=> 'lopd_check1', 'texto'=> trans('area.booking.lopd_check1', ['responsable'=> ConfigHelper::config('name')]), 'required'=> true, 'html'=> true])
                        </div>

                        <div class="form-group">
                            @include('includes.form_checkbox', [ 'campo'=> 'lopd_check2', 'texto'=> trans('area.booking.lopd_check2', ['plataforma'=> ConfigHelper::plataformaApp()]), 'html'=> true ])
                        </div>

                        <div class="form-group">
                            @include('includes.form_checkbox', [ 'campo'=> 'lopd_check3', 'texto'=> trans('area.booking.lopd_check3'), 'html'=> true ])
                        </div>
                        
                    </div>
                    <div class="modal-footer">

                        <div class="form-group pull-right">
                            {!! Form::submit(trans('area.actualizar'), array('id'=> 'btnLOPD', 'class' => 'btn btn-success')) !!}
                        </div>
                        
                    </div>
                    {!! Form::close() !!}

                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->

        <script type="text/javascript">
            $(document).ready(function() {
                $('#lopd').modal({backdrop: 'static', keyboard: false}); 
            });
        </script>
        @endif
        
    @endif


    @if($usuario->es_viajero)
        @include('area.bookings', ['ficha'=> $usuario->viajero] )
    @elseif($usuario->es_tutor)
        <?php $y=1; ?>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
        @foreach($usuario->tutor->viajeros as $viajero)
            <li role="presentation" @if($y == 1) class="active" @endif ><a href="#{{$y}}" aria-controls="{{$y}}" role="tab" data-toggle="tab"><h4 class="text-capitalize">{{mb_strtolower($viajero->full_name)}} <small>({!! trans('area.viajero') !!})</small></h4></a></li>
            <?php $y++; ?>
        @endforeach
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <?php $y=1; ?>
            @foreach($usuario->tutor->viajeros as $viajero)
                <div role="tabpanel" class="tab-pane fade in @if($y == 1) active @endif " id="{{$y}}">
                    @if($viajero->bookings_area->count()>0)
                        @include('area.bookings', ['ficha'=> $viajero] )
                    @else
                        <p>{!! trans('area.nobookings') !!}</p>
                    @endif
                </div>
                <?php $y++; ?>
            @endforeach
        </div>
    @endif

<script type="text/javascript">

function checkLOPD(_callback)
{
  @if(!ConfigHelper::config('es_rgpd'))
    _callback();
    return;
  @endif

  chk1 = $('#lopd_check1').is(':checked');
  chk2 = $('#lopd_check2').is(':checked');
  chk3 = $('#lopd_check3').is(':checked');

  if(!chk1)
  {
    $mensaje = "{{trans('area.booking.lopd_check1_no')}}";

    bootbox.alert($mensaje);
    return;
  }

  $b2ret = true;

  if(!chk2 || !chk3)
  {
    $b2ret = false;
  }

  if(!chk2 && !chk3)
  {
    $mensaje = "{{trans('area.booking.lopd_check2y3_no')}}";
  }
  else if(!chk2)
  {
    $mensaje = "{{trans('area.booking.lopd_check2_no')}}";
  }
  else if(!chk3)
  {
    $mensaje = "{{trans('area.booking.lopd_check3_no')}}";
  }

  if(!$b2ret)
  {
    bootbox.confirm({
      title: "LOPD",
      message: $mensaje,
      buttons: {
        confirm: {
          label: "{{trans('area.booking.lopd_check_seguir')}}",
          className: 'btn-warning'
        },
        cancel: {
          label: "{{trans('area.booking.lopd_check_volver')}}",
          className: 'btn-success'
        }
      },
      callback: function (result) {
        if(result)
        {
          $b2ret = true;
          _callback();
        }
      }
    });
  }
  else
  {
    _callback();
  }

  return $b2ret;
}

$('#btnLOPD').click( function(e) {
    e.preventDefault();

    checkLOPD( function(e) {
        $('#frmLOPD').submit();
    });
});

</script>

@stop

resources/views/area/pocketguide.blade.php
@extends('layouts.area')


@section('breadcrumb')
    {!! Breadcrumbs::render('area.booking.pocketguide',$booking) !!}
@stop


@section('content')

    @include('manage.cursos.pocketguide', ['curso'=> $ficha, 'lang'=> $idioma, 'pdf' => false])

@stop